services:
  redis:
    image: redis:7.2
    command: redis-server --requirepass uniasselvi
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "uniasselvi", "ping"]
      start_period: 5s
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: uniasselvi
      POSTGRES_PASSWORD: uniasselvi
      POSTGRES_DB: uniasselvi_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U uniasselvi"]
      interval: 5s
      start_period: 5s

volumes:
  postgres_data:
  redis_data:

  